### ISSUE TITLE
 Mapping of basins from mesh to high-res ocean grid is HELLA slow.

### ISSUE THREAD

**Issue by v1kko** [IMAU-paleo/minimism#2]

**Comment by v1kko** [comment]
links to https://github.com/IMAU-paleo/UFEMISM/issues/45

**Comment by jbrnlz** [comment]
In the case of the ocean (OG issue in Ufe), that is a pre-processing thingy done (within the model for convenience) only once (still takes long, but one survives) and saved into an external file for later use, which solves the problem.

For a consistent remeshing with minimal information loss, however, mapping dHi_a or dHs_a from the mesh onto the reference topography would be done every single time a mesh is updated, which becomes prohibitive when the reference topo is defined on a high resolution grid (e.g. ANT@5km or finer).

Idea: Use the output grid (lower res) as a surrogate/bridge between the mesh and the reference topo grid (high res). Even when there could be a loss of info when mapping from the high-res mesh onto the lower-res output grid, for the purposes of identifying a "grounding zone" it should be enough. As a bonus, if the output grid and the reference topo grid are "multiples" of each other, the mapping gets easy-peasy. As a double bonus, routines for mapping between grids already exist and can be recycled from IMAU-ICE.
